#!/usr/bin/env python3

import sys

import yaml


# Fix for YAML 1.2 spec, needed for kube-prometheus
# Source: https://github.com/yaml/pyyaml/issues/89
def construct_value(load, node):
    if not isinstance(node, yaml.ScalarNode):
        raise yaml.constructor.ConstructorError(
            'while constructing a value',
            node.start_mark,
            'expected a scalar, but found %s' % node.id, node.start_mark,
        )
    yield str(node.value)


yaml.SafeLoader.add_constructor('tag:yaml.org,2002:value', construct_value)


def replace_text_in_lines(lines, strings_to_replace):
    replaced_lines = []

    for line in lines.splitlines():
        for match, replace in strings_to_replace.items():
            line = line.replace(match, replace)
        replaced_lines.append(line)

    return '\n'.join(replaced_lines)


if __name__ == '__main__':
    with open(sys.argv[1], 'r') as f:
        config = yaml.load(f, Loader=yaml.SafeLoader)

    for k8s_object in yaml.safe_load_all(sys.stdin):
        k8s_yaml = yaml.dump(k8s_object, default_flow_style=False)

        if k8s_object['kind'] in config['objectKindsToReplace']:
            k8s_yaml = replace_text_in_lines(k8s_yaml, config['stringsToReplace'])

        print('---')
        print(k8s_yaml)
